#general
train_fe: False
fe_save_path: 'runs/fe_ae_model32_e50.pt'
save_path: 'runs/slece_model_test_e20_new_loss.pt'
gpu:
  - -1

#dataset
#ros_bag_path: '../../data/hilti/rosbag/exp03_stairs/exp03_construction_stairs.bag'
ros_bag_path: '../../data/hilti/rosbag/exp06_imu/exp06_construction_upper_level_3.bag'
ground_truth_path : '../../data/hilti/rosbag/exp05_imu/exp_05_construction_upper_level_2_imu.txt'
data_dir: 'dataset/data'
# ae dataset
# train_data_dir: 'dataset/data/ae_data'
# test_data_dir: 'dataset/data/ae_val_data'
# flow model dataset
train_data_dir: 'dataset/data/data_exp_04'
test_data_dir: 'dataset/data/data_exp_05'
field_name: 'x, y, intensity'
gen_gt: False

#lidarparameter
lidar_param:
  height: 32 # from hilti 2022 benchmark paper
  width: 1024 # from hilti 2022 benchmark paper
  h_res: 0.18  # horizontal resolution (10Hz setting) - width
  v_res: 1  # vertical res - height
  v_fov: # Field of view (-ve, +ve) along vertical axis - height
    down: -16
    up: 15

#imu_data
lidar_to_imu:
  translation :
    - -0.001
    - -0.00855
    - 0.055
  rotation :
    - 0.7071068
    - -0.7071068
    - 0
    - 0

#hyperparameter
learning_rate: 1e-4
weight_decay: 5e-4
epoch: 5