#general
train_fe: True
gpu:
  - -1
dataset_choice: 4
datasets:
  - 'exp01'
  - 'exp02'
  - 'exp03'
  - 'exp04'
  - 'exp05'
  - 'exp06'
  - 'synth_data'

#dataset creation
dataset:
  synth_data:
    path: '../../data/hilti/rosbag/exp05_imu'
    ros_bag: 'exp05_construction_upper_level_2.bag'
    ground_truth: 'exp_05_construction_upper_level_2_imu.txt'
    data_dir: '../dataset/synth_data2'
    generate_ground_truth: True
  exp05:
    path: '../../data/hilti/rosbag/exp05_imu'
    ros_bag: 'exp05_construction_upper_level_2.bag'
    ground_truth : 'exp_05_construction_upper_level_2_imu.txt'
    data_dir: '../dataset/exp05_xyz2'
    generate_ground_truth: False
    mean: 5.2251
    std: 9.6430
  exp04:
    path: '../../data/hilti/rosbag/exp04_imu'
    ros_bag: 'exp04_construction_upper_level.bag'
    ground_truth: 'exp_04_construction_upper_level_imu.txt'
    data_dir: '../dataset/exp04'
    generate_ground_truth: True
  exp06:
    path: '../../data/hilti/rosbag/exp06_imu'
    ros_bag: 'exp06_construction_upper_level_3.bag'
    ground_truth: 'exp_06_construction_upper_level_3_imu.txt'
    data_dir: '../dataset/exp06'
    generate_ground_truth: True
  exp03:
    path: '../../data/hilti/rosbag/exp03_stairs'
    ros_bag: 'exp03_construction_stairs.bag'
    ground_truth: ''
    data_dir: '../dataset/exp03'
    generate_ground_truth: False
  exp02:
    path: '../../data/hilti/rosbag/exp02_multilevel'
    ros_bag: 'exp02_construction_multilevel.bag'
    ground_truth: ''
    data_dir: '../dataset/exp02'
    generate_ground_truth: False
  exp01:
    path: '../../data/hilti/rosbag/exp01_construction_ground_level'
    ros_bag: 'exp01_construction_ground_level.bag'
    ground_truth: ''
    data_dir: '../dataset/exp01'
    generate_ground_truth: False

correspondence:
  nearest_neighbor: 0.2
  pair_distance:
    - 0.01
    - 1

# Auto encoder
autoencoder:
  save_path: 'fe_ae_darknet_full.pt'
  learning_rate: 0.01
  weight_decay: 0.0001
  momentum: 0.9          # sgd momentum
  epoch: 50
  wup_epochs: 1
  lr_decay: 0.995        # learning rate decay per epoch after initial cycle (from min lr)
  ckpt_interval: 10
  early_stopping: 10
  enable_wandb: False
  params:
    in_channel: 1
    dropout: 0.01
    bn_d: 0.01
    OS: 16
    model: 21

# flow model
s2lece:
  save_path: 'slece_model_test_e5_new_opt.pt'
  field_name: 'x, y, z, intensity'
  learning_rate: 0.01
  weight_decay: 0.0001
  momentum: 0.9          # sgd momentum
  mixed_precision: True
  clip: 1.0
  epoch: 10
  wup_epochs: 1
  lr_decay: 0.995        # learning rate decay per epoch after initial cycle (from min lr)
  batch_size: 2
  ckpt_interval: 2
  early_stopping: 10
  enable_wandb: True
  epsilon: 1e-8
  params:
    embedded_dim: 32
    dropout: 0.0

#lidarparameter
lidar_param:
  height: 32 # from hilti 2022 benchmark paper
  width: 2000
  h_res: 0.18  # horizontal resolution (10Hz setting) - width
  v_res: 1  # vertical res - height
  v_fov: # Field of view (-ve, +ve) along vertical axis - height
    down: -16
    up: 15

#imu_data
lidar_to_imu:
  translation :
    - -0.001
    - -0.00855
    - 0.055
  rotation :
    - 0.7071068
    - -0.7071068
    - 0
    - 0
