#general
save_path: 'runs/flow_mode1_e5.pt'
gpu:
  - -1

#dataset
ros_bag_path: '../../data/hilti/rosbag/exp04_imu/exp04_construction_upper_level.bag'
ground_truth_path : '../../data/hilti/rosbag/exp04_imu/exp_04_construction_upper_level_imu.txt'
data_dir: 'dataset/data_new_20'
field_name: 'x, y, intensity'

#lidarparameter
lidar_param:
  height: 32 # from hilti 2022 benchmark paper
  width: 1024 # from hilti 2022 benchmark paper
  h_res: 0.18  # horizontal resolution (10Hz setting) - width
  v_res: 1  # vertical res - height
  v_fov: # Field of view (-ve, +ve) along vertical axis - height
    down: -16
    up: 15

#imu_data
lidar_to_imu:
  translation :
    - -0.001
    - -0.00855
    - 0.055
  rotation :
    - 0.7071068
    - -0.7071068
    - 0
    - 0

#hyperparameter
learning_rate: 1e-4
weight_decay: 5e-4
epoch: 5
reliability_thr: 0.9
repeatability_thr: 0.9