#dataset
ros_bag_path: '../../data/hilti/rosbag/exp04_imu/exp04_construction_upper_level.bag'
ground_truth_path : '../../data/hilti/rosbag/exp04_imu/exp_04_construction_upper_level_imu.txt'
data_dir: 'dataset/data_new_new'
field_name: 'x, y, intensity'

#imu_data
translation_lidar_imu : np.array([-0.001, -0.00855, 0.055])
rotation_lidar_imu : np.array([0.7071068, -0.7071068, 0, 0])